### ISSUE TITLE
problems with using standard input

### ISSUE THREAD

**Issue by AUAShen** [SegataLab/panphlan#13]
Dear panphlan developers,

I am having problem when using standard input in Panphlan 3.0. 

Error is in the source code panphlan_map.py (https://github.com/SegataLab/panphlan/blob/3.0/panphlan_map.py), line 59-63. It examines the input, assuming it is a filename(string).  But the default input type is stdin and it will raise an error in "if not os.path.exists(args.input)" Are there any suggestions for this issue?

Thank you in advance for the help!

Best wishes,
AuAs

**Comment by leonarDubois** [comment]
Hello,

thanks for pointing out this issue. Indeed the arguments checking was incorrect. I pushed a tiny fix. Just testing if the input is stdin before looking for filename. Let me know if this is enough to solve your problem (I hope).

**Comment by AUAShen** [comment]
> Hello,
> 
> thanks for pointing out this issue. Indeed the arguments checking was incorrect. I pushed a tiny fix. Just testing if the input is stdin before looking for filename. Let me know if this is enough to solve your problem (I hope).

Thank you for the quick reply and fix! I think there is still a problem with input. In mapping function, when it check_input, it still assumes that the input is a string. (line 196: preprocess_cmd = check_input(args.input)), because in function check_input, (line 107) the method endswith is assuming a str. 

Best wishes,
Shen

**Comment by leonarDubois** [comment]
Hi, 

actually, I'm focusing on fixes for the official 3.0 release atm
I just pushed a new tiny correction. Just one more check. There might be another one needed for the bowtie2 call, but let's see if it work without...

**Comment by AUAShen** [comment]
Hi Leonar,

Thank you for the reply! That's very helpful. Looking forward to the official 3.0 release.

Best wishes,
Shen
